### ISSUE TITLE
Is it possible to change the url of a barcode campaign after its creation?

### ISSUE THREAD

**Issue by mohammadali-bacha** [devdreamsolution/laravel7-qrcode-campaign#21]
Hello, I would like to be able to modify the links of the qrcodes after having created them but it seems to me that it would be necessary to add the option to save on the frontend and make the link in the backend to save in the database.

How to do it ?

**Comment by devdreamsolution** [comment]
Hi @mohammadali-bacha , thanks to use our script.
So do you want to go to the new modified link using already generated QR code?

**Comment by mohammadali-bacha** [comment]
Yes, I just want to be able to modify the link on the already generated QR codes

**Comment by devdreamsolution** [comment]
That's possible, we have to add the functionality to redirect new URL in tracking module.

**Comment by fusignbc** [comment]
how to install this could you please share some documentation.

thankyou.

**Comment by devdreamsolution** [comment]
/public_html in the cPanel Terminal or Putty

```
git clone https://github.com/devdreamsolution/laravel7-qrcode-campaign.git .
composer install
cp .env.example .env
php artisan key:generate
php artisan storage:link
```
Open .env file and setup database connection and others.
