### ISSUE TITLE
Copyright infringement - copied design in repository

### ISSUE THREAD

**Issue by ajayts07** [devdreamsolution/laravel7-qrcode-campaign#22]
Hello,

I hope this message finds you well. I am writing to you because I have noticed that your repository, https://github.com/boelchan/vuexy-laravel-livewire, appears to have copied our template design without permission.

We ([Pixinvent](https://themeforest.net/user/pixinvent)) are the original creators of the design, and we do not allow unauthorized reproductions. We kindly ask that you remove the repository or change the design to avoid copyright infringement.

I have attached evidence of the copied design for your reference. Please let us know your thoughts on this matter, and we can work together to resolve it.

![image](https://user-images.githubusercontent.com/105908323/231966945-6998ffaf-50cf-46a5-b2be-6fc865c30805.png)
![image](https://user-images.githubusercontent.com/105908323/231967023-85cb477a-e767-438a-839f-c63a32698bd7.png)
![image](https://user-images.githubusercontent.com/105908323/231967076-3d7531e9-156b-428b-b7b0-06787f7c3996.png)

Thank you for your understanding.

Best regards,
Ajay

**Comment by devdreamsolution** [comment]
Hi Ajay,
I don't understand what you say.
Is this (https://github.com/boelchan/vuexy-laravel-livewire) your repository?
![image](https://github.com/devdreamsolution/laravel7-qrcode-campaign/assets/54434088/c054242c-6aa1-4165-902b-9490efa68c47)
Look at the commit time.

![image](https://github.com/devdreamsolution/laravel7-qrcode-campaign/assets/54434088/bb617b16-352b-45fe-a7a5-a25bd5b452a5)
My commit time is the long ago, so I think I developed long time ago.
:)

**Comment by devdreamsolution** [comment]
I will close this issue.
